api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("api/subscriptions/", views.add_subscription,
         name="add_subscription"),
    path("api/subscriptions/<int:author_id>/", views.remove_subscription,
         name="remove_subscription"),
    path("api/favorites/", views.add_favorites,
         name="add_favorites"),
    path("api/favorites/<int:recipe_id>/", views.remove_favorites,
         name="remove_favorites"),
    path("api/purchases/", views.add_purchase,
         name="add_purchase"),
    path("api/purchases/<int:recipe_id>/", views.remove_purchase,
         name="remove_purchase"),
    path("<str:username>/<int:recipe_id>/remove/", views.recipe_remove,
         name="recipe_remove"),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.flatpages import views
from django.conf.urls import handler404, handler500 # noqa

handler404 = "recipes.views.page_not_found" # noqa
handler500 = "recipes.views.server_error" # noqa

urlpatterns = [
    path('about-author/', views.flatpage, {'url': '/about-author/'},
         name='about-author'),
    path("admin/", admin.site.urls),
    path('about/', include('django.contrib.flatpages.urls')),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'},
         name='about-spec'),

    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),

    path("", include("recipes.urls")),
    path("", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index,
         name="index"),
    path("recipe_new/", views.recipe_add_page,
         name="recipe_add_page"),
    path("subscription/", views.subscription,
         name="subscription"),
    path("favorites/", views.favorites,
         name="favorites"),
    path("purchases/", views.purchases_page,
         name="purchases_page"),
    path("purchases/download/", views.purchases_download,
         name="purchases_download"),
    path("<str:username>/", views.user_recipe_view_page,
         name="user_recipe_view_page"),
    path("<str:username>/<int:recipe_id>/", views.recipe_view_page,
         name="recipe_view_page"),
    path("<str:username>/<int:recipe_id>/edit/", views.recipe_edit_page,
         name="recipe_edit_page"),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название")
    unit = models.CharField(max_length=255, verbose_name="Мера измерения")

    def __str__(self):
        return self.title


class IngredientAmount(models.Model):
    amount = models.IntegerField(verbose_name="Кол-во")
    ingredient = models.ForeignKey("Ingredient", on_delete=models.CASCADE)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)


class Tag(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название")
    slug = models.SlugField(max_length=255, unique=True, verbose_name="Slug")
    color = models.CharField(max_length=255, verbose_name="Цвет")

    def __str__(self):
        return self.slug


class Recipe(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes"
    )
    title = models.CharField(max_length=255, verbose_name="Название")
    image = models.ImageField(upload_to="image/", verbose_name="Путь до файла")
    description = models.TextField(verbose_name="Описание")
    ingredient = models.ManyToManyField(
        Ingredient, through=IngredientAmount
    )
    tags = models.ManyToManyField(Tag, related_name="recipes")
    cooking_time = models.IntegerField(
        default=10, verbose_name="Время приготовления")
    pub_date = models.DateTimeField(
        "date published", auto_now_add=True, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-pub_date", )

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ("title", "tags", "cooking_time", "description", "image")

recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import F, Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import RecipeForm
from .models import Ingredient, IngredientAmount, Recipe
from .utils import get_favorites, get_ingredients

User = get_user_model()


def index(request):

    tags = request.GET.get("tags", "")

    if tags:
        recipes = Recipe.objects.filter(
            tags__slug__in=tags.split(",")
        ).select_related(
            "author"
        ).prefetch_related(
            "tags"
        ).distinct()
    else:
        recipes = Recipe.objects.all()

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    if request.user.is_authenticated:
        favorites = get_favorites(request)
        purchases = Recipe.objects.filter(
            purchase_recipe__user=request.user)
    else:
        favorites, purchases = [], []

    return render(request, "index.html", {
        "page": page,
        "paginator": paginator,
        "tags": tags,
        "favorites": favorites,
        "purchases": purchases,
        "is_index_page": True,
    })


@login_required
def subscription(request):
    user = request.user
    authors = User.objects.filter(
        following__follower=user).prefetch_related("recipes").order_by('-id')

    paginator = Paginator(authors, 6)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    return render(request, "subscription.html", {
        "page": page,
        "paginator": paginator,
        "is_subscription_page": True,
    })


@login_required
def favorites(request):

    tags = request.GET.get("tags", "")

    if tags:
        recipes = Recipe.objects.filter(
            favorite_recipe__user=request.user
        ).filter(
            tags__slug__in=tags.split(",")
        ).distinct()
    else:
        recipes = Recipe.objects.filter(
            favorite_recipe__user=request.user
        )

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    favorites = get_favorites(request)
    purchases = Recipe.objects.filter(purchase_recipe__user=request.user)

    return render(request, "favorites.html", {
        "page": page,
        "paginator": paginator,
        "tags": tags,
        "favorites": favorites,
        "purchases": purchases,
        "is_favorites_page": True,
    })


def user_recipe_view_page(request, username):

    tags = request.GET.get("tags", "")
    author = get_object_or_404(User, username=username)

    if tags:
        recipes = Recipe.objects.filter(
            author_id=author.id
        ).filter(
            tags__slug__in=tags.split(",")
        ).distinct()
    else:
        recipes = Recipe.objects.filter(author_id=author.id)

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)

    if request.user.is_authenticated:
        favorites = get_favorites(request)
        purchases = Recipe.objects.filter(
            purchase_recipe__user=request.user)
    else:
        favorites, purchases = [], []

    return render(request, "user_recipe_view_page.html", {
        "page": page,
        "paginator": paginator,
        "author": author,
        "tags": tags,
        "favorites": favorites,
        "purchases": purchases,
    })


def recipe_view_page(request, username, recipe_id):

    recipe = get_object_or_404(Recipe, id=recipe_id, author__username=username)
    ingredients = IngredientAmount.objects.filter(recipe_id=recipe_id)
    author = get_object_or_404(User, username=username)

    if request.user.is_authenticated:
        favorites = get_favorites(request)
        purchases = Recipe.objects.filter(
            purchase_recipe__user=request.user)
    else:
        favorites, purchases = [], []

    return render(request, "recipe_view_page.html", {
        "author": author,
        "recipe": recipe,
        "ingredients": ingredients,
        "favorites": favorites,
        "purchases": purchases,
    })


@login_required
def recipe_edit_page(request, username, recipe_id):

    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if request.user != recipe.author or username != request.user.username:
        return redirect("recipe_view_page",
                        username=recipe.author, recipe_id=recipe.pk)

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        ingredients = get_ingredients(request)

        if not bool(ingredients):
            form.add_error(None, "Добавьте хотя бы один ингредиент")

        elif form.is_valid():
            form.save()
            recipe.ingredientamount_set.all().delete()
            ingredient_amounts = [
                IngredientAmount(
                    amount=amount,
                    ingredient=get_object_or_404(Ingredient, title=title),
                    recipe=recipe
                ) for title, amount in ingredients.items()
            ]
            IngredientAmount.objects.bulk_create(ingredient_amounts)
            return redirect("recipe_view_page",
                            username=recipe.author, recipe_id=recipe.pk)

    form = RecipeForm(instance=recipe)
    ingredients = IngredientAmount.objects.filter(recipe_id=recipe_id)

    return render(request, "recipe_edit_page.html",
                  {"form": form, "recipe": recipe, "ingredients": ingredients})


@login_required
def recipe_add_page(request):

    if request.method == "POST":
        form = RecipeForm(request.POST, files=request.FILES)
        ingredients = get_ingredients(request)

        if not bool(ingredients):
            form.add_error(None, "Добавьте хотя бы один ингредиент")

        elif form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            ingredient_amounts = [
                IngredientAmount(
                    amount=amount,
                    ingredient=get_object_or_404(Ingredient, title=title),
                    recipe=recipe
                ) for title, amount in ingredients.items()
            ]

            IngredientAmount.objects.bulk_create(ingredient_amounts)
            form.save_m2m()
            return redirect("recipe_view_page",
                            username=request.user, recipe_id=recipe.id)
    else:
        form = RecipeForm()
    return render(request, "recipe_add_page.html",
                  context={"form": form, "is_recipe_new_page": True})


@login_required
def purchases_page(request):
    recipes = Recipe.objects.filter(purchase_recipe__user=request.user)
    return render(request, "purchases_page.html",
                  {"recipes": recipes, "is_purchases_page": True})


@login_required
def purchases_download(request):

    recipes = Recipe.objects.filter(purchase_recipe__user=request.user)
    ingredients = recipes.annotate(
        name=F("ingredient__title"),
        dimension=F("ingredient__unit")
    ).values("name", "dimension").annotate(
        total=Sum("ingredientamount__amount")).order_by("name")

    res = ["name | dimension | total"]
    for ingredient in ingredients[1:]:
        name = ingredient["name"]
        dimension = ingredient["dimension"].replace("\r", "")
        total = ingredient["total"]
        res.append(f"{name} | {dimension} | {total}")

    response = HttpResponse("\n".join(res), content_type="text/txt")
    response["Content-Disposition"] = "attachment; filename='purchases.txt'"

    return response


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(
        request,
        "misc/500.html",
        status=500
    )

recipes/templates/purchases_page.html
{% extends "base.html" %}

{% block title %}
    <title>Список покупок</title>
{% endblock %}

{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block content %}
    <main class="main container">

        {% csrf_token %}
        <div class="main__header">
            <h1 class="main__title">Список покупок</h1>
        </div>

        <div class="card-list card-list_column">
            <ul class="shopping-list">

                {% for recipe in recipes %}
                    <li class="shopping-list__item" data-id="{{ recipe.id }}">
                        <div class="recipe recipe_reverse">

                            {% load thumbnail %}
                            {% thumbnail recipe.image "364x240" crop="center" upscale=True as im %}
                                <img src="{{ im.url }}" alt="{{ recipe.title }}" class="recipe__image recipe__image_big">
                            {% endthumbnail %}

                            <h3 class="recipe__title">
                                <a style="color: #000" href="{% url 'recipe_view_page' recipe.author recipe.pk %}">
                                    {{ recipe.title }}
                                </a>
                            </h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                        </div>
                        <button class="button shopping-list__button link">Удалить</button>
                    </li>
                {% endfor %}

            </ul>
            <a class="button button_style_light-blue" href="{% url 'purchases_download' %}">Скачать список</a>
        </div>

    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'shopList.js' %}"></script>
{% endblock %}

recipes/templates/recipe_add_page.html
{% extends 'base.html' %}

{% block title %}
    <title> Создание рецепта </title>
{% endblock %}

{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
    <main class="main container">

        <div class="main__header">
            <h1 class="main__title">Создание рецепта</h1>
        </div>

        <div class="form-container">
            <form class="form" method="post" enctype="multipart/form-data" id="main-form">
                {% csrf_token %}
                {% load user_filters %}

                <div class="form__group">
                    <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        {{ form.title|addclass:"form__input" }}
                        {% if form.errors %}
                            {% for error in form.title.errors %}
                                <span class="form__error">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">
                            {% for tag_choice, tag_value in form.tags.field.choices %}
                                <div class="tags__item">
                                    <input
                                        type="checkbox"
                                        name="tags"
                                        value="{{ tag_choice.instance.pk }}"
                                        id="id_{{ tag_choice.instance.slug }}"
                                        class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}"
                                        {% if tag_choice.instance in form.instance.tags.all %} checked {% endif %}>
                                    <label for="id_{{ tag_choice.instance.slug }}"
                                    class="tags__label">{{ tag_choice.instance.title }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        {% if form.errors %}
                            {% for error in form.tags.errors %}
                                <span class="form__error">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">{{ form.ingredient.unit }}</label>
                        </div>
                        <div class="form__field-group-ingredientes-container">
                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    </div>
                </div>

                <div class="form__group">
                    <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        {{ form.cooking_time|addclass:"form__input" }}
                        <label for="id_cooking_time" class="form__label">минут</label>
                        {% if form.errors %}
                            {% for error in field.errors %}
                                <span class="form__error">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="form__group">
                    <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
                    <div class="form__field-group">
                        {{ form.description|addclass:"form__textarea" }}
                        {% if form.errors %}
                            {% for error in field.errors %}
                                <span class="form__error">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>

                    <div class="form__field-group">
                        {{ form.image|addclass:"form__file-button" }}
                        {% if form.errors %}
                            {% for error in form.errors %}
                                <span class="form__error">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>

                </div>

                <div class="form__footer">
                    <button class="button button_style_blue" type="submit" id="submit-button">Создать рецепт</button>
                </div>

            </form>
        </div>

    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipe_edit_page.html
{% extends "base.html" %}

{% block title %}
    <title> Редактирование рецепта </title>
{% endblock %}

{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Редактирование рецепта</h1>
        </div>

        <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% load user_filters %}

            <div class="form__group">
                <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    {% if form.errors %}
                        {% for error in form.title.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag_choice, tag_value in form.tags.field.choices %}
                            <div class="tags__item">
                                <input
                                    type="checkbox"
                                    name="tags"
                                    value="{{ tag_choice.instance.pk }}"
                                    id="id_{{ tag_choice.instance.slug }}"
                                    class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}"
                                    {% if tag_choice.instance in form.instance.tags.all %} checked {% endif %}>
                                <label for="id_{{ tag_choice.instance.slug }}"
                                class="tags__label">{{ tag_choice.instance.title }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    {% if form.errors %}
                        {% for error in form.tags.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                            {% for ingredient in ingredients.all %}
                                <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                                    <span>
                                        {{ ingredient.ingredient.title }} {{ ingredient.amount }} {{ ingredient.ingredient.unit }}
                                    </span>
                                    <span class="form__field-item-delete"></span>

                                    <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.title }}">
                                    <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.amount }}">
                                    <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.unit }}">
                                </div>
                            {% endfor %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>

            <div class="form__group">
                <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time|addclass:"form__input" }}
                    <label for="id_cooking_time" class="form__label">минут</label>
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form__group">
                <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.image|addclass:"form__file-button" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form__footer">
                <button class="button button_style_blue" type="submit" id="submit-button">Сохранить рецепт</button>
                <a style="margin-left: 2.5em" href="{% url 'recipe_remove' recipe.author.username recipe.id %}" class="form__ingredient-link">Удалить</a>
            </div>

        </form>
    </div>
    </main>
{% endblock %}

{% block js %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/subscription.html
{% extends 'base.html' %}

{% block title %}
    <title> Мои подписки </title>
{% endblock %}

{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block content %}
     <main class="main container">

        <div class="main__header">
            <h1 class="main__title">Мои подписки</h1>
        </div>

        <div class="card-list">
            {% csrf_token %}

            {% for user in page %}
                <div class="card-user" data-author="{{ user.id }}">
                    <div class="card-user__header">
                        <h2 class="card-user__title">
                            <a style="color: #000" href="{% url 'user_recipe_view_page' user.username %}">{{ user.get_full_name }}</a>
                        </h2>
                    </div>

                    <div class="card-user__body">
                        <ul class="card-user__items">
                            {% for recipe in user.recipes.all|slice:'3' %}
                                <li class="card-user__item">
                                <div class="recipe">
                                    <img src="{{ recipe.image.url }}" alt="какой-то-текст" class="recipe__image">
                                    <h3 class="recipe__title"><a style="color: #000" href="{% url 'recipe_view_page' user.username recipe.pk %}">{{ recipe.title }}</a></h3>
                                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                                </div>
                                </li>
                            {% endfor %}

                            {% if user.recipes.count > 3 %}
                                <li class="card-user__item">
                                    <a href="{% url 'user_recipe_view_page' user.username %}" class="card-user__link link">Еще {{ user.recipes.count|add:'-3' }} рецептов...</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>

                    <div class="card-user__footer">
                        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
                    </div>
                </div>
          {% endfor %}
        </div>

        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator %}
        {% endif %}

    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'myFollow.js' %}"></script>
{% endblock %}